apps/blog/urls.py
from django.contrib import admin
from django.urls import path
from apps import *
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'
urlpatterns = [
    path('', PostList.as_view(), name='blog_posts'),
    path('<str:tag>/', PostList.as_view(), name='blog_post_by_tag'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

naszdzien/urls.py
from django.contrib import admin
from django.urls import path
from apps import *
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls', namespace='landingpage')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('produkty/', include('products.urls', namespace='products')),
    path('', include('admin_adminlte.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from unidecode import unidecode


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    image = models.ImageField(upload_to='blog/')
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    slug = models.SlugField(allow_unicode=True, max_length=200, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    view_count = models.IntegerField(default=0)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class PostTag(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name='tag_posts')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='tag_posts')

    def __str__(self):
        return f'{self.tag} - {self.post}'

apps/blog/views.py
from django.shortcuts import render
from .models import Post, Tag
from django.views import generic
from products.models import Package, Product

class BlogMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_post = self.get_latest_post()

        tag = self.kwargs.get('tag')
        most_popular_posts = self.get_most_popular_posts(tag)

        context.update({
            'products': self.get_products(),
            'latest_post': latest_post,
            'the_most_popular_posts': most_popular_posts,
            'tags': Tag.objects.all(),
            'current_tag': Tag.objects.get(name=tag) if tag else None,
        })


        return context

    def get_queryset(self):
        queryset = Post.objects.filter(status='published').order_by('-created')

        tag = self.kwargs.get('tag')
        if tag:
            queryset = queryset.filter(tag_posts__tag__name=tag)

        return queryset

    def get_latest_post(self):
        return Post.objects.filter(status='published').order_by('-created').first()

    def get_most_popular_posts(self, tag=None):
        if tag:
            return Post.objects.filter(status='published').filter(tag_posts__tag__name=tag).order_by('-view_count')[:3]

        return Post.objects.filter(status='published').order_by('-view_count')[:3]

    def get_products(self):
        return Product.objects.filter(show_on_landing_page=True, active=True)


# Create your views here.
class PostDetail(BlogMixin, generic.DetailView):
    model = Post
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        post = self.get_object()

        post.view_count += 1
        post.save()

        return super().get(request, *args, **kwargs)

    def get_most_popular_posts(self, tag=None):
        if self.get_object().tag_posts.exists():
            post = self.get_object()
            tags = post.tag_posts.all().values_list('tag', flat=True).distinct()
            posts_with_same_tags = Post.objects.filter(status='published').exclude(id=post.id).filter(tag_posts__tag__in=tags).distinct().order_by('-view_count')[:3]

            if posts_with_same_tags.count() > 0:
                return posts_with_same_tags


        return Post.objects.filter(status='published').order_by('-view_count')[:3]


class PostList(BlogMixin, generic.ListView):
    model = Post
    context_object_name = 'posts'
    ordering = ['-created']
    paginate_by = 5

apps/blog/templates/base/categories.html
<div class="col-lg-12 col-md-6">
    <div class="widget">
      <h2 class="section-title mb-3">Kategorie</h2>
      <div class="widget-body">
        <ul class="widget-list">
            {% for tag in tags %}
              <li>
                  <a href="{% url 'blog:blog_post_by_tag' tag.name %}">{{ tag.name }} <span class="ml-auto">({{ tag.tag_posts.count }})</span></a>
              </li>
            {% endfor %}
        </ul>
      </div>
    </div>
  </div>

apps/blog/templates/base/recommended_posts.html
<div class="col-lg-12 col-md-6">
    <div class="widget">
      <h2 class="section-title mb-3">Polecane</h2>
      <div class="widget-body">
        <div class="widget-list">
            {% for post in the_most_popular_posts %}
                {% if forloop.counter == 1 %}
                  <article class="card mb-4">
                    <div class="card-image">
                      <div class="post-info"> <span class="text-uppercase">Może Ci się spodobać</span>
                      </div>
                      <img loading="lazy" decoding="async" src="{{ post.image.url }}" alt="Post Thumbnail" class="w-100">
                    </div>
                    <div class="card-body px-0 pb-1">
                      <h3><a class="post-title post-title-sm"
                          href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                      <p class="card-text">{{ post.description }}</p>
                      <div class="content"> <a class="read-more-btn" href="{{ post.get_absolute_url }}">Przeczytaj</a>
                      </div>
                    </div>
                  </article>
                {% else %}
                  <a class="media align-items-center" href="{{ post.get_absolute_url }}">
                    <img loading="lazy" decoding="async" src="{{ post.image.url }}" alt="Post Thumbnail" class="w-100">
                    <div class="media-body ml-3">
                      <h3 style="margin-top:-5px">{{ post.title }}</h3>
                      <p class="mb-0 small">{{ post.description }}</p>
                    </div>
                  </a>
                {% endif %}
            {% endfor %}
        </div>
      </div>
    </div>
</div>