apps/blog/urls.py
from django.contrib import admin
from django.urls import path
from apps import *
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'
urlpatterns = [
    path('', PostList.as_view(), name='blog_posts'),
    path('<str:tag>/', PostList.as_view(), name='blog_post_by_tag'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/landingpage/urls.py
from django.contrib import admin
from django.urls import path
from apps import *
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = 'landingpage'
urlpatterns = [
    path('', LandingPageView.as_view(), name='landing-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/urls.py
from django.contrib import admin
from django.urls import path
from apps import *
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'products'

urlpatterns = [
    path('<str:slug>/', ProductDetail.as_view(), name='product_detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

naszdzien/urls.py
from django.contrib import admin
from django.urls import path
from apps import *
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls', namespace='landingpage')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('produkty/', include('products.urls', namespace='products')),
    path('', include('admin_adminlte.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from pygments.lexer import default


class Feature(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name

class ProductMixin(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    price = models.FloatField()
    discount_percentages = models.DecimalField(max_digits=3, decimal_places=0)
    estimated_setup_time_by_user = models.CharField(max_length=50, default="10 minut")
    estimated_setup_time_by_system = models.CharField(max_length=50, default="<1 minuta")
    features = models.ManyToManyField(Feature, null=True)
    active = models.BooleanField(default=False)
    support = models.BooleanField(default=False)
    customizable = models.BooleanField(default=True)

    class Meta:
        abstract = True

    def get_price(self):
        return self.price * (100-float(self.discount_percentages))/100 if self.discount_percentages else self.price


class Product(ProductMixin):
    show_on_landing_page = models.BooleanField(default=False)

    slug = models.SlugField(allow_unicode=True, max_length=200, unique=True, blank=True)


    class Meta:
        ordering = ['price']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.slug])


def create_product_image_path(instance, filename):
    name, ext = filename.split('.')
    file_path = 'products/{product}/photos.{ext}'.format(
        product=instance.product, ext=ext)
    return file_path

class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=create_product_image_path)
    alt = models.CharField(max_length=50)


class Package(ProductMixin):
    products = models.ManyToManyField(Product)
    main_rgb_color = models.CharField(max_length=10, default='#FFFFFF')
    secondary_rgb_color = models.CharField(max_length=10, default='#FFFFFF')

    slug = models.SlugField(allow_unicode=True, max_length=200, unique=True, blank=True)

    class Meta:
        ordering = ['price']
        verbose_name = 'Package'
        verbose_name_plural = 'Packages'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        super(Package, self).save(*args, **kwargs)

apps/products/views.py
from django.shortcuts import render
from django.views import generic
from products.models import Product, Package
from django.templatetags.static import static
from blog.models import Post

# Create your views here.
class ProductDetail(generic.DetailView):
    model = Product
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        invitations = [
            {
                'name': 'Zaproszenie na wesele',
                'image_path': 'img/invitations/wesele.png',
            },
            {
                'name': 'Zaproszenie na 18stkę',
                'image_path': 'img/invitations/18stka.png',
            },
            {
                'name': 'Zaproszenie na imprezę biznesową',
                'image_path': 'img/invitations/biznes.png',
            },
            {
                'name': 'Zaproszenie na wesele',
                'image_path': 'img/invitations/wesele.png',
            },
            {
                'name': 'Zaproszenie na 18stkę',
                'image_path': 'img/invitations/18stka.png',
            },
            {
                'name': 'Zaproszenie na imprezę biznesową',
                'image_path': 'img/invitations/biznes.png',
            },
        ]
        packages = Package.objects.filter(active=True).order_by('price').all()
        faq_questions = [
            {
                'question': 'Co to jest zaproszenie elektroniczne?',
                'answer': 'Zaproszenie elektroniczne to cyfrowa forma tradycyjnego zaproszenia, która jest wysyłana za pomocą poczty elektronicznej, wiadomości SMS, mediów społecznościowych lub innych platform komunikacyjnych online. Jest to wygodne, szybkie i ekologiczne rozwiązanie dla organizacji różnego rodzaju wydarzeń.'
            },
            {
                'question': 'Jakie są zalety korzystania z zaproszeń elektronicznych?',
                'answer': 'Zaproszenia elektroniczne oferują kilka korzyści, w tym: szybkość wysyłki, ekologię, możliwość personalizacji oraz śledzenie odpowiedzi gości. Dodatkowo, są one bardziej opłacalne w porównaniu do tradycyjnych zaproszeń papierowych.'
            },
            {
                'question': 'Czy mogę personalizować moje zaproszenie elektroniczne?',
                'answer': 'Tak, oferujemy paletę gotowych szablonów zaproszeń. Można je edytować w programach graficznych i wrzucić przerobioną wersję, lub użyć gotowego szablonu.'
            },
            {
                'question': 'Czy zaproszenie elektroniczne można wysłać na różne sposoby?',
                'answer': 'Tak, zaproszenia elektroniczne można wysyłać za pomocą poczty elektronicznej, mediów społecznościowych, aplikacji do komunikacji (np. WhatsApp) lub SMS-a, w zależności od preferencji i dostępnych narzędzi.'
            },
            {
                'question': 'Jakie informacje powinno zawierać zaproszenie elektroniczne?',
                'answer': 'Tutaj panuje pełna dowolność, standardowe zaproszenie elektroniczne powinno zawierać nazwę wydarzenia, datę i godzinę, miejsce, oraz dodatkowe informacje, takie jak instrukcje dojazdu, agenda wydarzenia, oraz możliwość potwierdzenia obecności (RSVP).'
            },
            {
                'question': 'Czy zaproszenia elektroniczne są bezpieczne?',
                'answer': 'Tak, zaproszenia elektroniczne są bezpieczne, stosujemy zaawansowane mechanizmy zabezpieczeń, chroniące dane Twoje i Gości wydarzenia.'
            },
            {
                'question': 'Czy mogę załączyć pliki do mojego zaproszenia elektronicznego?',
                'answer': 'Tak, możesz załączyć całe zaproszenie lub załączyć pliki do szablonu, takie jak zdjęcia, mapy, dokumenty czy inne materiały, które mogą być przydatne dla gości.'
            },
            {
                'question': 'Jakie są koszty związane z wysyłaniem zaproszeń elektronicznych?',
                'answer': 'Koszt zaproszeń elektronicznych zależy od wybranego zakresu funkcji. Niektóre podstawowe opcje są dostępne za darmo, ale za bardziej zaawansowane funkcje mogą być naliczane dodatkowe opłaty.'
            },
            {
                'question': 'Czy mogę śledzić, kto otworzył moje zaproszenie?',
                'answer': 'Tak, oferujemy darmową usługę, która pozwala reagować na zaproszenia i śledzić aktualne odpowiedzi gości wydarzenia.'
            }
        ]
        blog_posts = Post.objects.filter(tag_posts__tag__name=self.object.name).filter(status='published').order_by('-view_count').all()[:3]

        context.update({
            'products': self.get_products(),
            'invitations': invitations,
            'packages': packages,
            'faq_questions': faq_questions,
            'blog_posts': blog_posts
        })


        return context


    def get_products(self):
        return Product.objects.filter(show_on_landing_page=True, active=True)

apps/products/templates/products/invitations.html
{% load static %}

<style>
    .swiper {
      width: 100%;
      padding-top: 50px;
      padding-bottom: 50px;
    }

    .swiper-slide {
      background-position: center;
      background-size: cover;
      width: 300px;
      height: 300px;
    }

    .swiper-slide img {
      display: block;
      width: 100%;
    }

    .invitation {
        height: 550px;
        padding: 10px;
        background-color: #fff;
        box-shadow: 0 5px 25px rgba(0, 0, 0, 0.3);
        position: relative;
    }

    .invitation h5 {
        position: absolute;
        bottom: 100px;
        width: 100%;
        left: 0;
        text-align: center;
    }

    .invitation a {
        position: absolute;
        bottom: 50px;
        left: 13%;
        width: 74%;
        text-align: center;
    }

    main img {
        max-height: 500px;
        width: 100%;
        object-fit: cover;
        object-position: 100% 25%;
    }

    .invitation-button:hover {
        color: white;
    }

    .accordion-button:not(.collapsed) {
        color: black;
        background-color: #fffaea;
    }

    .accordion-button:focus {
        border-color: #fffaea !important;
        box-shadow: 0 0 0 .25rem #fff5d4;
    }

</style>

<main>
	<section class="section">
		<div class="container">
        <img loading="lazy" decoding="async" src="{% static 'img/invitations/phone-with-invitation-3.svg' %}" alt="{{ product_image.alt }}">
			<div class="row">
				<div class="col-lg-12">
                    <h1 class="mt-4">{{ product.name }}</h1>
                    <span>
                        Jest to nowoczesne narzędzie umożliwiające wysyłanie spersonalizowanych zaproszeń na różnego rodzaju wydarzenia za pośrednictwem internetu. Ta forma komunikacji z gośćmi zyskuje coraz większą popularność, szczególnie w dobie cyfryzacji i wzrastającej świadomości ekologicznej. W tym artykule przeprowadzimy Cię przez wszystkie aspekty związane z tworzeniem, wysyłaniem i zarządzaniem zaproszeniami online, od korzyści po ceny i funkcje personalizacji.
                    </span>

                    <h4 class="mt-4">Spis treści</h4>
                    <ul>
                        <li><a href="#korzysci">Korzyści z wykorzenia zaproszeń elektronicznych</a></li>
                        <li><a href="#rodzaje">Rodzaje zaproszeń</a></li>
                        <li><a href="#proces_tworzenia">Jak działa proces tworzenia zaproszenia elektronicznego?</a></li>
                        <li><a href="#funkcje_i_personalizacja">Funkcje i Opcje Personalizacji</a></li>
                        <li><a href="#przyklady">Przykłady i inspiracje</a></li>
                        <li><a href="#Oferta">Oferta</a></li>
                        <li><a href="#opinie">Opinie i referencje klientów</a></li>
                        <li><a href="#faq">FAQ - Najczęściej Zadawane Pytania</a></li>
                        <li><a href="#integracja">Integracje i Współpraca z Inny Mi Narzędziami</a></li>
                        <li><a href="#pomoc">Pomoc i Wsparcie Techniczne</a></li>
                        <li><a href="#blog">Blog i aktualności</a></li>
                    </ul>


                    <h2 class="mt-4" id="korzysci">Korzyści z wykorzystania zaproszeń elektronicznych</h2>
                    <span>
                        Zaproszenia elektroniczne przynoszą wiele korzyści zarówno organizatorom wydarzeń, jak i zaproszonym gościom. Przykłady przedstawiamy poniżej:
                        <ul>
                            <li>
                                <h3>Oszczędność czasu i pieniędzy</h3>
                                <span>
                                    Nasze rozwiązanie eliminuje konieczność drukowania, pakowania oraz wysyłki lub osobistego dostarczenia zaproszeń tradycyjnych
                                </span>
                            </li>

                            <li>
                                <h3>Personalizacja</h3>
                                <span>
                                    Zaproszenia można personalizować pod każdego gościa lub po wydarzenie. Można samodzielnie stworzyć szablon zaproszenia lub wybrać gotowy wariant i go edytować
                                </span>
                            </li>

                            <li>
                                <h3>Komunikacja</h3>
                                <span>Goście po otrzymaniu zaproszenia na wydarzenie mogą dodać je do kalendarza w telefonie, oraz zaznaczyć czy wezmą udział</span>
                            </li>

                            <li>
                                <h3>Ekologiczność</h3>
                                <span>Brak konieczności drukowania tradycyjnych zaproszeń jest proekologiczne, ostatecznie tradycyjne zaproszenia i tak się gubią...</span>
                            </li>

                        </ul>
                    </span>

                    <h2 class="mt-4" id="rodzaje">Rodzaje zaproszeń</h2>
                    <span>
                        Dzięki możliwościom personalizacji, zaproszenie elektroniczne można wysłać na każde wydarzenie.

                        <div class="swiper invitations-swiper">
                            <div class="swiper-wrapper">
                                {% for invitation in invitations %}
                                  <div class="swiper-slide invitation" style="background-color: #f9f9f9;">
                                    <img src="{% static invitation.image_path %}" alt="przykład zaproszenia"/>
                                    <h5>{{ invitation.name }}</h5>
                                    <a href="#" type="button" class="btn btn-block btn-outline-warning btn-sm invitation-button font-bold">Personalizuj</a>
                                  </div>
                                {% endfor %}
                            </div>
                          </div>


                    </span>

                    <h2 class="mt-4" id="proces_tworzenia">Jak działa proces tworzenia zaproszenia elektronicznego?</h2>
                    <span>
                        Tworzenia zaproszenia jest proste i intuicyjne.
                        <ol>
                            <li>Wybór lub wysłanie szablonu zaproszenia,</li>
                            <li>Dodanie listy gości,</li>
                            <li>Wybór sposobu dostawy zaproszenia.</li>
                        </ol>
                        Całość pokazana jest na <a href="#pomoc">poradniku</a>.
                    </span>

                    <h2 class="mt-4" id="funkcje_i_personalizacja">Funkcje i Opcje Personalizacji</h2>
                    <span>
                        Personalizacja odbywa się poprzez pobranie przykładowego zaproszenia oraz edycja tego elementu w edytorze graficznym (np. <a
                            href="https://www.canva.com/">canva</a>). Można również wysłać gotowe już zaproszenie, które musi zawierać odpowiednio opisane fragmenty.
                    </span>
                    <span>
                        Możliwe jest wysłanie różnych zaproszeń do różnych gości. Ogranicza nas tylko wyobraźnia!
                    </span>

                    <h2 class="mt-4" id="oferta">Oferta</h2>
                    {% include 'landingpage/offer.html' with disable_header=True %}

                    <h2 class="mt-4" id="opinie">Opinie i referencje klientów</h2>
                    <span>
                        Przed podjęciem decyzji o wyborze platformy do zaproszeń online, warto zapoznać się z opiniami innych użytkowników. Wiele firm publikuje na swoich stronach referencje od zadowolonych klientów oraz opinie użytkowników na temat oferowanych usług. Dobre recenzje mogą być decydującym czynnikiem przy wyborze najlepszej opcji.
                    </span>


                    <h2 class="mt-4" id="faq">FAQ - Najczęściej Zadawane Pytania</h2>
                    <div class="accordion accordion-flush" id="faq-accordion">
                        {% for faq_question in faq_questions %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="flush-heading-{{ forloop.counter }}">
                                    <button class="accordion-button collapsed font-weight-bold" style="font-size: 18px;" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-{{ forloop.counter }}" aria-expanded="false" aria-controls="flush-collapse-{{ forloop.counter }}">
                                        {{ faq_question.question }}
                                    </button>
                                </h2>
                                <div id="flush-collapse-{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="flush-heading-{{ forloop.counter }}" data-bs-parent="#accordionFlushExample">
                                    <div class="accordion-body">
                                        {{ faq_question.answer }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <h2 class="mt-4" id="integracja">Integracje i Współpraca z Innymi Narzędziami</h2>
                    <span>
                        Nasza aplikacja współpracuje z większością komunikatorów, pozwala to na wysłanie zaproszenia za pomocą mediów społecznościowych, email'a, whatsup'a jak i SMS'a.<br>
                        Umożliwiamy również edycję naszych zaproszeń w Canvie, jak i dodawanie gotowych już szablonów z tej strony. <br>
                        Nasz Panel Użytkownika dostosowany jest do logowania kilkoma źródłami danych, tak aby rejestracja i logowanie były szybkie i przyjemne. <br>

                    </span>

                    <h2 class="mt-4" id="pomoc">Pomoc i Wsparcie Techniczne</h2>
                    <span>
                        Wsparcie techniczne jest dostępne od poniedziałku do soboty w godzinach 8-20 na infolinii pod numerem telefonu <b>+48 572 912 761</b>.<br>
                        W pakietach zawierających wsparcie techniczne, jest możliwość zaplanowania rozmowy, i ustalenia tematu z góry. Taka rozmowa ma na celu nie tylko wytłumaczenie działania, ale również umożliwia stworzenie produktu przez naszych programistów tak aby odpowiadał on Państwa wymaganiom.
                    </span>

                    <h2 class="mt-4" id="blog">Blog i Aktualności</h2>
                    {% include 'landingpage/blog.html' with disable_header=True %}

                </div>
			</div>
		</div>
	</section>
</main>

apps/products/templates/products/product_detail.html
{% extends 'landingpage/base/page.html' %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock extra_css %}

{% block header %}
    {% url 'landingpage:landing-page' as landing_page_url %}
    {% url 'blog:blog_posts' as blog_href %}
    {% include "landingpage/base/header.html" with main_href=landing_page_url about_us_href=landing_page_url|add:"#o-nas" products_href=landing_page_url|add:'#produkty' offer_href=landing_page_url|add:'#oferta' blog_href=blog_href login_href='#' register_href=landing_page_url|add:'#' %}
{% endblock header %}


{% block content %}
    {% if product.name == 'Zaproszenia Elektroniczne' %}
        {% include 'products/invitations.html' %}
    {% else %}
    {% endif %}
{% endblock content %}


{% block footer %}
    {% url 'landingpage:landing-page' as landing_page_url %}
    {% url 'blog:blog_posts' as blog_href %}
    {% include 'landingpage/base/footer.html' with actual_blog_posts_href=blog_href|add:"#najnowsze" blog_href=blog_href login_href="#" register_href="#" %}
{% endblock footer %}


{% block extra_js %}
    <script>
        var swiper = new Swiper(".invitations-swiper", {
          effect: "coverflow",
          grabCursor: true,
          loop: true,
          centeredSlides: true,
          slidesPerView: "auto",
          coverflowEffect: {
            rotate: 50,
            stretch: 0,
            depth: 100,
            modifier: 1,
            slideShadows: true,
          },
        });
  </script>
{% endblock extra_js %}